export const routes = {
  home: '/',
  dashboard: '/dashboard',
  chat: '/chat',
  roadmap: '/roadmap',
  login: '/auth/login',
  register: '/auth/register',
  characters: '/characters',
  character: (id: number) => `/characters/${id}`,
  user: (id: number) => `/users/${id}`,
  users: '/users',
  characterCreate: '/characters/create',
  accountSettings: '/users/account-settings',
  characterClasses: '/info/dnd-classes',
  characterRaces: '/info/dnd-races',
};
